### ISSUE TITLE
Installing help

### ISSUE THREAD

**Issue by mostm** [Andr3wHur5t/mcat#2]
Sorry for creating a new issue, but you should add any instructions on how to install this tool

**Comment by ShadowFM** [comment]
It should be pretty easy, upload the files and simply type the command
`npm install`
In the folder where you have the package.json file

**Comment by ThatLurker** [comment]
@mostm 
Clone the repor with `git clone https://github.com/Andr3wHur5t/mcat.git` 
`cd` into the directory and run `npm install ` and after that just run `node index.js`

**Comment by mostm** [comment]
Waking up an over year old issue...
I did manage it to work, but I referred that these things should be mentioned in README. (You know: Installing Node.JS, Downloading repo, installing node module)
